site_name: FHIR Aggregator
site_description: Search with FHIR
site_url: https://fhir-aggregator.readthedocs.io/
repo_url: https://github.com/FHIR-Aggregator/helpdesk

theme:
  logo: assets/home.svg
  name: material
  custom_dir: overrides
  font:
    text: noto sans
  docs_dir: docs
  palette: 
    primary: teal
    accent: teal
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - announce.dismiss
    - content.code.copy

plugins:
  - search
  - mkdocs-jupyter:
      remove_tag_config:
          remove_input_tags:
              - hide_code
      include_source: True
      execute: True #make false to render site quickly by not running notebook code
      allow_errors: True #make false to validate all notebook code works

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

 # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
  - index.md
  - Getting Started:
    - getting_started/index.md
    - Query in the Cloud: getting_started/cloud.md
    - Download our query tool: getting_started/install.md
    - Query with curl: getting_started/curl.ipynb
  - Documentation:
    - fhir-aggregator: documentation/fhiraggregatorintro.ipynb
    - fhir-query:
        - fhir-query man page: documentation/fhirqueryman.ipynb
        - fhir-query: documentation/fhirquery.ipynb
    - FHIR-Aggregator Vocabulary:
       - Accessing the Vocabulary: documentation/vocabulary.ipynb
       - Visualize search results: documentation/heatmaps.ipynb
       - Using FHIR extensions: documentation/fhirextensions.ipynb
       - Vobabulary filtering examples: documentation/filterexamples.ipynb
  - About Us:
    - about_us/index.md
    - about_us/ourdata.md
    - about_us/how_we_etal.md

